// columnDescriptions.ts

export const columnDescriptionsTH: Record<string, string> = {
  no: "ลำดับที่ / Running number",
  group_name: "ชื่อกลุ่มของผู้ใช้งาน",
  username: "ชื่อผู้ใช้งาน (Username)",
  action: "การกระทำที่ผู้ใช้ทำ",
  action_date_time: "วันและเวลาที่มีการดาวน์โหลด/อัปโหลดไฟล์",
  detail: "รายละเอียดของไฟล์ที่ดาวน์โหลด/อัปโหลด",
  bu: "หน่วยธุรกิจ (Business Unit) ที่เกี่ยวข้อง",
  position: "ตำแหน่งของผู้ใช้งาน",
  resigned_date: "วันที่ลาออก (ถ้ามี)",
  days_after_action: "จำนวนวันหลังจากเกิดเหตุการณ์",
  event_type: "ประเภทของเหตุการณ์ (ปกติ / ผิดปกติ)",
  download_more_10_files_day: "การดาวน์โหลดไฟล์มากกว่า 10 ไฟล์ต่อวัน",
  unauthorized: "การเข้าถึงที่ไม่ได้รับอนุญาต",
  employee_resigning_within_one_month: "พนักงานที่กำลังจะลาออกภายใน 1 เดือน",
  is_bu_dcc: "เป็น BU DCC หรือไม่",
  admin_confirm: "ผู้อนุมัติ / ยืนยัน",
  admin_confirm_date: "วันที่ยืนยัน",
  admin_confirm_edit: "ผู้ที่แก้ไขการยืนยัน",
  admin_edit_confirm_date: "วันที่แก้ไขการยืนยัน",
  admin_confirm_comment: "ความคิดเห็น / หมายเหตุจากผู้ยืนยัน",
  admin_confirm_event: "เหตุการณ์ที่ได้รับการยืนยัน",
  manage: "จัดการ / แก้ไขข้อมูล",
};

export const columnDescriptionsEN: Record<string, string> = {
  no: "Running number",
  group_name: "User group name",
  username: "User Name download/upload",
  action: "Action download/upload ",
  action_date_time: "Date and time of the file download/upload.",
  detail: "Details of the file download/upload.",
  bu: "Business Unit",
  position: "User Position",
  resigned_date: "Resignation date (if any)",
  days_after_action: "Number of days after the action occurred",
  event_type: "Type of event (Usual / Unusual)",
  download_more_10_files_day: "Large download (more than 10 files in a day)",
  unauthorized: "Unauthorized access attempts",
  employee_resigning_within_one_month:
    "Employee scheduled to resign within one month",
  is_bu_dcc: "Whether the user belongs to BU DCC",
  admin_confirm: "Confirmed by",
  admin_confirm_date: "Confirmation date",
  admin_confirm_edit: "Edited by",
  admin_edit_confirm_date: "Edit confirmation date",
  admin_confirm_comment: "Comments or notes",
  admin_confirm_event: "Confirmed event type",
  manage: "Manage / Edit record",
};
