export const columnDescriptionsEN: Record<string, string> = {
  no: "Running number",
  emp_no: "Employee number",
  emp_email: "Employee email",
  plant_name: "Plant Name",
  fullname: "First and last Name",
  app_Names: "Application Name",
  is_email: "Email Notifications",
  is_accept: "Show save button",
  is_review: "show Review button",
  is_export: "show Export excel",
  created_by: "Admin Create By",
  created_date: "Admin Create Date",
  updated_by: "Admin Update By",
  updated_date: "Admin Update Date",
  status: "Status",
};
